name: PlayHard Entertainment
favicon: null
layout_spectrum: 0.8692923043854535
typography_spectrum: 0.3495622824411839
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1f1a17'
    - '#ff0000'
    - '#838281'
    - '#ff8181'
  brandStrength: 0.625
  lightness: 0.375
  saturation: 0.2934055831283331
  rhythmicContrast: 0.5
purpose: []
