name: PlayHard Entertainment
favicon: null
layout_spectrum: 0.13047
typography_spectrum: 0.4699
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1f1a17'
    - '#fe0000'
    - '#c1c0bf'
    - '#fe3737'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
