name: PlayHard Entertainment
favicon: null
layout_spectrum: 0.50703
typography_spectrum: 0.4699
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1f1a17'
    - '#ff0000'
    - '#838281'
    - '#ff8181'
  brandStrength: 1
  lightness: 0.25
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
